# Configuration for Label Actions - https://github.com/dessant/label-actions

# When the `bug` label is added to issues
bug:
  issues:
  # Post a comment
    comment: >
      Thanks for using ArchR! Please make sure that your post belongs in the Issues section! This is where bugs and error reports belong. <br />
      Usage questions and feature requests should be posted in the [Discussions](https://github.com/GreenleafLab/ArchR/discussions) section, not in Issues.<br /><br />
      __Before we help you, you must respond to the following questions__ unless your original post already contained this information:<br />
      __1.__ Can you recapitulate your error using the tutorial code and dataset? If so, provide a reproducible example.<br />
      __2.__ If you've encountered an error, have you already searched the full manual and previous Issues to make sure that this hasn't already been solved?<br />
      __3.__ Did you post your log file? If not, add it now.<br />
      
# When the `new_discussion` label is added to discussions
#new_discussion:
#  discussions:
#    # Post a comment
#    comment: >
#      Thanks for using ArchR! This is a discussion post
